name       : paraview
version    : 5.9.0
release    : 17
homepage   : https://www.paraview.org/
source     :
    - https://www.paraview.org/files/v5.9/ParaView-v5.9.0.tar.xz : b03258b7cddb77f0ee142e3e77b377e5b1f503bcabc02bfa578298c99a06980d
license    : BSD-3-Clause
component  : office.scientific
summary    : Data analysis and visualization
description: |
    ParaView is an open-source, multi-platform data analysis and visualization application. ParaView users can quickly build visualizations to analyze their data using qualitative and quantitative techniques. The data exploration can be done interactively in 3D or programmatically using ParaView’s batch processing capabilities.
    ParaView was developed to analyze extremely large datasets using distributed memory computing resources. It can be run on supercomputers to analyze datasets of exascale size as well as on laptops for smaller data.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(eigen3)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libtiff-4)
    - pkgconfig(netcdf)
    - pkgconfig(protobuf)
    - pkgconfig(pugixml)
    - pkgconfig(python3)
    - pkgconfig(theora)
    - pkgconfig(xcursor)
    - cgns-devel
    - double-conversion-devel
    - gl2ps-devel
    - hdf5-devel
    - libharu-devel
    - utfcpp
libsplit   : no
setup      : |
    # Disable version check for libharu - 2.4.0 is unreleased, and we have backported necessary patches
    sed -i "s/VERSION 2.4.0//g" VTK/ThirdParty/libharu/CMakeLists.txt

    %cmake_ninja \
        -DPARAVIEW_BUILD_WITH_EXTERNAL=ON \
        -DPARAVIEW_USE_PYTHON=ON
build      : |
    # Warning the build takes ~1.5GB RAM per Core for building
    %ninja_build
install    : |
    %ninja_install
