name       : paraview
version    : 5.8.0
release    : 13
homepage   : https://www.paraview.org/
source     :
    - https://www.paraview.org/files/v5.8/ParaView-v5.8.0.tar.xz : 219e4107abf40317ce054408e9c3b22fb935d464238c1c00c0161f1c8697a3f9
license    : BSD-3-Clause
component  : office.scientific
summary    : Data analysis and visualization
description: |
    ParaView is an open-source, multi-platform data analysis and visualization application. ParaView users can quickly build visualizations to analyze their data using qualitative and quantitative techniques. The data exploration can be done interactively in 3D or programmatically using ParaView’s batch processing capabilities.
    ParaView was developed to analyze extremely large datasets using distributed memory computing resources. It can be run on supercomputers to analyze datasets of exascale size as well as on laptops for smaller data.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(eigen3)
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(jsoncpp)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libtiff-4)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(theora)
    - pkgconfig(xt)
    - double-conversion-devel
    - gl2ps-devel
    - pugixml-devel
libsplit   : no
setup      : |
    # Disable version check - GL2PS 1.4.1 isn't released, but we have both patches that VTK wants.
    sed -i "s/VERSION 1.4.1//" VTK/ThirdParty/gl2ps/CMakeLists.txt

    %cmake_ninja \
        -DPARAVIEW_USE_PYTHON=ON \
        -DVTK_MODULE_USE_EXTERNAL_ParaView_protobuf=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_doubleconversion=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_eigen=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_expat=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_freetype=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_glew=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_jpeg=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_jsoncpp=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_libxml2=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_lz4=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_lzma=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_ogg=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_png=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_pugixml=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_theora=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_tiff=ON \
        -DVTK_MODULE_USE_EXTERNAL_VTK_zlib=ON
build      : |
    # Warning the build takes ~1.5GB RAM per Core for building
    %ninja_build
install    : |
    %ninja_install
