name       : paraview
version    : 5.6.0
release    : 2
homepage   : https://www.paraview.org/
source     :
    - git|https://gitlab.kitware.com/paraview/paraview.git : v5.6.0
license    : BSD-3-Clause
component  : office.scientific
summary    : VTK-based Data Analysis and Visualization Application
description: |
    ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(freetype2)
    - pkgconfig(hdf5-1.10.3)
    - pkgconfig(jsoncpp)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libtiff-4)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xt)
    - pugixml-devel
rundeps    :
    - pygments
libsplit   : no
setup      : |
    %cmake_ninja -DPARAVIEW_ENABLE_PYTHON=ON \
                 -DVTK_PYTHON_VERSION=3 \
                 -DVTK_USE_SYSTEM_EIGEN=ON \
                 -DVTK_USE_SYSTEM_EXPAT=ON \
                 -DVTK_USE_SYSTEM_FREETYPE=ON \
                 -DVTK_USE_SYSTEM_HDF5=ON \
                 -DVTK_USE_SYSTEM_JSONCPP=ON \
                 -DVTK_USE_SYSTEM_JPEG=ON \
                 -DVTK_USE_SYSTEM_LIBXML2=ON \
                 -DVTK_USE_SYSTEM_LZ4=ON \
                 -DVTK_USE_SYSTEM_LZMA=ON \
                 -DVTK_USE_SYSTEM_PNG=ON \
                 -DVTK_USE_SYSTEM_PROTOBUF=ON \
                 -DVTK_USE_SYSTEM_PUGIXML=ON \
                 -DVTK_USE_SYSTEM_PYGMENTS=ON \
                 -DVTK_USE_SYSTEM_TIFF=ON \
                 -DVTK_USE_SYSTEM_ZLIB=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
